### PR TITLE
PR: TODO List project 

### PR DESCRIPTION
**Pull request by umairarshadbutt**
TODO List in JavaScript(and Webpack) is a practice project, which includes managing the dynamically DOM manipulation. I used Javascript, HTML5, CSS3, Bootsrap and Webpack to implement it.

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @umairarshadbutt**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] the application is to be separated in modules, meaning every function responsible for a certain action should be put in it's own file. 
- [ ] DOM-Manipulation and Logic are in separate modules. 
- [ ] the application is supposed to be using webpack to run the project in development mode or create a build.
- [ ] every project should have a due date. 
- [ ] the user should be able to create project., then create todos using those projects.
- [ ] the user should be able to display the todos depending on the project selected.
- [ ] your file structure is incorrect, for example, js file's are not assets.

to get a clear idea of what the project should behave, how webpack is supposed to be set up and how the file structure should look like, take a look at [this ](https://github.com/mahmoud717/todo-list)project for guidance. 
p.s. this project's webpack setup is a bit complex, so you can stick to your own while adding these scripts to it:
```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```  

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- I see that you are trying to implement all the requirements asking by the previous tse  :+1:

To Improve :factory_worker:

- [ ] It will be nice if your read again the lesson about webpack, please, check this lesson [webpack](https://microverse.pathwright.com/library/javascript-module-v10-copy/166786/path/step/97635161/) then, apply it in your project. It is very important because your file and folder structure are incorrect.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
## Status: Changes requested :red_circle: 

### Hello @umairarshadbutt :wave: 

### Thank you for making all of the requested changes, but there's still one thing we need to fix:

- [x] Your ESlint checks are failing, please fix this issue :smile: 

Kindly make the requested changes and submit them for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Review by arslanbisharat — APPROVED** [review]
# Approved :clap:

Hello Developer, wave:

Thank You for submitting this Pull Request. I am thrilled to announce that your project has met all the minimum requirements and now it is approved. :clap:

I am wishing you very good luck with the next project. :smile:

Once again, Congratulations!:joy:

**Best,
Arslan Bisharat(PT-TSE)
Slack: @arslanbisharat**

**Pull request merged**
